### ISSUE TITLE
GMZ option + Clarify Support of GML

### ISSUE THREAD

**Issue by chris03-dev** [Animelici804/understudio#2]
Hello, Animelici!

It would be nice if a .gmz/.yyz file would be provided in a future release, as importing the project would be extremely simple with a single file. As far as I know, importing .gmz/.yyz files is available within GameMaker.

Speaking of GameMaker, what version does this project support? There is GameMaker: Studio 2, GameMaker: Studio, and GameMaker 8, and I'm a little confused on whether it will even work on the version in my computer...

Edit: I forgot that GMS2 export files were actually .yyz files. My apologies for the misunderstanding. 
I have now inserted the term ".yyz" throughout my comment to compensate.

**Comment by Animeliqite** [comment]
GMZ/GMX support will come later on, after its initial release (when everything is done basically). The project is supported on the beta version of Game Maker Studio 2.3.0, so therefore I don't know if it's supported on your Game Maker version. But don't worry, like I said, GMS 1.4 support will come when everything is done.

**Comment by chris03-dev** [comment]
Wow, thanks for your time! 
I just saw the changes you've made in your README file, and I believe that will be enough to ease my concerns. Hoping to get GM:S 1.4 support not too long in the future.

By the way, I noticed that my decision of opening an issue here gave you the motivation after all : )

Anyway, closing this issue now.

**Comment by Animeliqite** [comment]
You're welcome.
